name: Update GitHub Streak

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  streak:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Streak Stats
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          username: dk-khandelwal06
          output_path: profile/streak.svg
